title: "Kazdov's Blog"
description: "Bitácora de un futuro pentester"
url: "https://originalkazdov.github.io"
baseurl: "" # no lo toques

author:
  name: "Kazdov"
  bio: "Estudiando para el eJPT. Blog personal sobre ciberseguridad."
  location: "Argentina"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/OriginalKazdov"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/KazdovEth"

defaults:
  # POSTS individuales dentro de _posts/
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      share: true
      header:
        og_image: /assets/images/link_preview_image.png

  # PÁGINAS personalizadas como /about/, /blog/, etc.
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      author_profile: true
      header:
        og_image: /assets/images/link_preview_image.png

collections:
  pages:
    output: true
    permalink: /:path/

theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

navigation:
  header:
    - label: "Inicio"
      url: /
    - label: "Sobre mí"
      url: /about/

minimal_mistakes_skin: "dark"

analytics:
  provider: "custom"
